SCENE = ChHd.md scene001.txt  scene102.txt  scene103.txt scene105.txt   scene106.txt  scene107.txt  scene108.txt scene110.txt scene111.txt scene112.txt

Chapter01.md: $(SCENE)
	cat $(SCENE) >Chapter01.md
